version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "49301:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: guygoldi
      MYSQL_DATABASE: BookNail
      MYSQL_USER: bookNail_user
      MYSQL_PASSWORD: guygoldi123$

  app:
    build:
        context: .
        dockerfile: Miritush.API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__BooksDB=server=db;user=bookNail_user;password=guygoldi123$;database=BookNail;port=3306