// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Miritush.DAL.Model;

namespace Miritush.DAL.Migrations
{
    [DbContext(typeof(booksDbContext))]
    [Migration("20220217071014_booknail")]
    partial class booknail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Miritush.DAL.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("BookID");

                    b.Property<int?>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("CustomerID")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("Durtion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ServiceID")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ServiceTypeID")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("StartAt")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("BookId");

                    b.HasIndex(new[] { "CustomerId" }, "CustomerID_idx");

                    b.HasIndex(new[] { "ServiceId" }, "ServiceID_idx");

                    b.HasIndex(new[] { "ServiceTypeId" }, "ServiceTypeID_idx");

                    b.HasIndex(new[] { "BookId", "StartDate" }, "StartDate")
                        .IsUnique();

                    b.ToTable("books");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Bookscancel", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BookID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int(11)")
                        .HasColumnName("CustomerID");

                    b.Property<int>("Durtion")
                        .HasColumnType("int(11)");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ServiceID")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ServiceTypeID")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("StartAt")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("WhyCancel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("whyCancel")
                        .HasDefaultValueSql("'NULL'");

                    b.HasIndex(new[] { "CustomerId" }, "CustomerIDX");

                    b.HasIndex(new[] { "ServiceId" }, "ServiceIDX");

                    b.HasIndex(new[] { "ServiceTypeId" }, "ServiceTypeIDX");

                    b.ToTable("bookscancel");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Closeday", b =>
                {
                    b.Property<int>("CloseDaysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("CloseDaysID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("CloseDaysId")
                        .HasName("PRIMARY");

                    b.ToTable("closedays");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("CustomerID");

                    b.Property<sbyte?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasDefaultValueSql("'''#c96d9f'''");

                    b.Property<string>("FirstName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("LastName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("Otp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("OTP")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("PhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("CustomerId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("HolidayID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'NULL'")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.HasKey("HolidayId");

                    b.ToTable("holidays");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Lockhour", b =>
                {
                    b.Property<int>("IdLockHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idLockHours");

                    b.Property<int>("EndAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("StartAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("IdLockHours")
                        .HasName("PRIMARY");

                    b.ToTable("lockhours");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ServiceID");

                    b.Property<string>("ServiceName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("ServiceId");

                    b.ToTable("services");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Servicetype", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ServiceTypeID");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("Duration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ServiceID");

                    b.Property<string>("ServiceTypeName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("ServiceTypeId");

                    b.HasIndex(new[] { "ServiceId" }, "ServiceID_idx")
                        .HasDatabaseName("ServiceID_idx1");

                    b.ToTable("servicetype");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Setting", b =>
                {
                    b.Property<string>("SettingName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SettingValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(5000)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("SettingName")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SettingName" }, "SettingName")
                        .IsUnique();

                    b.ToTable("settings");
                });

            modelBuilder.Entity("Miritush.DAL.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Workhour", b =>
                {
                    b.Property<int>("DayOfWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("CloseTime")
                        .HasColumnType("int(11)");

                    b.Property<int>("OpenTime")
                        .HasColumnType("int(11)");

                    b.HasKey("DayOfWeek")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DayOfWeek" }, "DayOfWeek_UNIQUE")
                        .IsUnique();

                    b.ToTable("workhours");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Book", b =>
                {
                    b.HasOne("Miritush.DAL.Model.Customer", "Customer")
                        .WithMany("Books")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("CustomerID");

                    b.HasOne("Miritush.DAL.Model.Service", "Service")
                        .WithMany("Books")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("ServiceID");

                    b.HasOne("Miritush.DAL.Model.Servicetype", "ServiceType")
                        .WithMany("Books")
                        .HasForeignKey("ServiceTypeId")
                        .HasConstraintName("ServiceTypeID");

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Bookscancel", b =>
                {
                    b.HasOne("Miritush.DAL.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("CustomerIDX")
                        .IsRequired();

                    b.HasOne("Miritush.DAL.Model.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("ServiceIDX");

                    b.HasOne("Miritush.DAL.Model.Servicetype", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .HasConstraintName("ServiceTypeIDX");

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Servicetype", b =>
                {
                    b.HasOne("Miritush.DAL.Model.Service", "Service")
                        .WithMany("Servicetypes")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("ServiceIDFK")
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Customer", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Service", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Servicetypes");
                });

            modelBuilder.Entity("Miritush.DAL.Model.Servicetype", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
